 import  { react,
 typescript,
 javascript,
 html,
 css,
 sass,
 tailwind,
 nodejs,
 express,
 nextjs,
 vue,
 vuetify,
 firebase,
 mongodb,
 mysql,
 postgresql,
 git,
 github,
 gitlab,
 vite,
 pwa,
 python,
 php,
 figma,
 redux,
 stripe,
 spring,
 threejs,
 r3,
 bootstrap,
 reactrouter,
 mongoose,
 bun,
 hono,
 coffeescript,
 webpack } from "@/components/icons/simple-icons/index";


export const SKILLS= {
  react: {
    color: "#61DAFB",
    label: "React",
    icon: react,
  },
  typescript: {
    color: "#007ACC",
    label: "TypeScript",
    icon: typescript,
  },
  javascript: {
    color: "#F7DF1E",
    label: "JavaScript",
    icon: javascript,
  },
  html: {
    color: "#E34F26",
    label: "HTML",
    icon: html,
  },
  css: {
    color: "#1572B6",
    label: "CSS",
    icon: css,
  },
  sass: {
    color: "#CC6699",
    label: "SASS",
    icon: sass,
  },
  tailwind: {
    color: "#06B6D4",
    label: "Tailwind",
    icon: tailwind,
  },
  node: {
    color: "#339933",
    label: "Node.js",
    icon: nodejs,
  },
  express: {
    color: "#000000",
    label: "Express.js",
    icon: express,
  },
  nextjs: {
    color: "currentColor",
    label: "Next.js",
    icon: nextjs,
  },
  vue: {
    color: "#4FC08D",
    label: "Vue.js",
    icon: vue,
  },
  vuetify: {
    color: "#1867C0",
    label: "Vuetify",
    icon: vuetify,
  },
  firebase: {
    color: "#FFCA28",
    label: "Firebase",
    icon: firebase,
  },
  spring: {
    color: "#6DB33F",
    label: "Spring",
    icon: spring,
  },
  threejs: {
    color: "#000000",
    label: "Three.js",
    icon: threejs,
  },
  r3: {
    color: "#000000",
    label: "React Three Fiber",
    icon: r3,
  },
  zustand: {
    color: "#000000",
    label: "Zustand",
    icon: redux,
  },
  bootstrap: {
    color: "#563D7C",
    label: "Bootstrap",
    icon: bootstrap,
  },
  reactrouter: {
    color: "#CA4245",
    label: "React Router",
    icon: reactrouter,
  },
  mongo: {
    color: "#47A248",
    label: "MongoDB",
    icon: mongodb,
  },
  mongoose: {
    color: "#47A248",
    label: "Mongoose",
    icon: mongoose,
  },
  bun: {
    color: "#000000",
    label: "Bun",
    icon: bun,
  },
  hono: {
    color: "#FF6B00",
    label: "Hono",
    icon: hono,
  },
  redux: {
    color: "#764ABC",
    label: "Redux",
    icon: redux,
  },
  stripe: {
    color: "#635BFF",
    label: "Stripe",
    icon: stripe,
  },
  java: {
    color: "#007396",
    label: "Java",
    icon: coffeescript,
  },
  mysql: {
    color: "#4479A1",
    label: "MySQL",
    icon: mysql,
  },
  postgresql: {
    color: "#336791",
    label: "PostgreSQL",
    icon: postgresql,
  },
  git: {
    color: "#F05032",
    label: "Git",
    icon: git,
  },
  github: {
    color: "#181717",
    label: "GitHub",
    icon: github,
  },
  gitlab: {
    color: "#FCA121",
    label: "GitLab",
    icon: gitlab,
  },
  webpack: {
    color: "#8DD6F9",
    label: "Webpack",
    icon: webpack,
  },
  vite: {
    color: "#646CFF",
    label: "Vite",
    icon: vite,
  },
  pwa: {
    color: "#5A0FC8",
    label: "PWA",
    icon: pwa,
  },
  python: {
    color: "#3776AB",
    label: "Python",
    icon: python,
  },
  php: {
    color: "#777BB4",
    label: "PHP",
    icon: php,
  },
  figma: {
    color: "#F24E1E",
    label: "Figma",
    icon: figma,
  },
};