 import  { react,
 typescript,
 javascript,
 html,
 css,
 sass,
 tailwind,
 nodejs,
 express,
 nextjs,
 vue,
 vuetify,
 firebase,
 mongodb,
 mysql,
 postgresql,
 git,
 github,
 gitlab,
 vite,
 pwa,
 python,
 php,
 figma,
 redux,
 stripe,
 spring,
 threejs,
 r3,
 bootstrap,
 reactrouter,
 mongoose,
 bun,
 hono,
 coffeescript,
 webpack,
 nestjs,
 typeorm,
 vercel,
 zod,
 modelcontextprotocol,
 huggingface,
 reactquery,
 shadcnui,
 netlify,
 cloudflarepages,
 googleanalytics,
 claude } from "@/components/icons/simple-icons/index";


export const SKILLS= {
  react: {
    color: "#61DAFB",
    label: "React",
    icon: react,
  },
  typescript: {
    color: "#007ACC",
    label: "TypeScript",
    icon: typescript,
  },
  javascript: {
    color: "#F7DF1E",
    label: "JavaScript",
    icon: javascript,
  },
  html: {
    color: "#E34F26",
    label: "HTML",
    icon: html,
  },
  css: {
    color: "#1572B6",
    label: "CSS",
    icon: css,
  },
  sass: {
    color: "#CC6699",
    label: "SASS",
    icon: sass,
  },
  tailwind: {
    color: "#06B6D4",
    label: "Tailwind",
    icon: tailwind,
  },
  node: {
    color: "#339933",
    label: "Node.js",
    icon: nodejs,
  },
  express: {
    color: "#000000",
    label: "Express.js",
    icon: express,
  },
  nextjs: {
    color: "currentColor",
    label: "Next.js",
    icon: nextjs,
  },
  vue: {
    color: "#4FC08D",
    label: "Vue.js",
    icon: vue,
  },
  vuetify: {
    color: "#1867C0",
    label: "Vuetify",
    icon: vuetify,
  },
  firebase: {
    color: "#FFCA28",
    label: "Firebase",
    icon: firebase,
  },
  spring: {
    color: "#6DB33F",
    label: "Spring",
    icon: spring,
  },
  threejs: {
    color: "#000000",
    label: "Three.js",
    icon: threejs,
  },
  r3: {
    color: "#000000",
    label: "React Three Fiber",
    icon: r3,
  },
  zustand: {
    color: "currentColor",
    label: "Zustand",
  },
  bootstrap: {
    color: "#563D7C",
    label: "Bootstrap",
    icon: bootstrap,
  },
  reactrouter: {
    color: "#CA4245",
    label: "React Router",
    icon: reactrouter,
  },
  mongo: {
    color: "#47A248",
    label: "MongoDB",
    icon: mongodb,
  },
  mongoose: {
    color: "#47A248",
    label: "Mongoose",
    icon: mongoose,
  },
  bun: {
    color: "#000000",
    label: "Bun",
    icon: bun,
  },
  hono: {
    color: "#FF6B00",
    label: "Hono",
    icon: hono,
  },
  redux: {
    color: "#764ABC",
    label: "Redux",
    icon: redux,
  },
  stripe: {
    color: "#635BFF",
    label: "Stripe",
    icon: stripe,
  },
  java: {
    color: "#007396",
    label: "Java",
    icon: coffeescript,
  },
  mysql: {
    color: "#4479A1",
    label: "MySQL",
    icon: mysql,
  },
  postgresql: {
    color: "#336791",
    label: "PostgreSQL",
    icon: postgresql,
  },
  git: {
    color: "#F05032",
    label: "Git",
    icon: git,
  },
  github: {
    color: "#181717",
    label: "GitHub",
    icon: github,
  },
  gitlab: {
    color: "#FCA121",
    label: "GitLab",
    icon: gitlab,
  },
  webpack: {
    color: "#8DD6F9",
    label: "Webpack",
    icon: webpack,
  },
  vite: {
    color: "#646CFF",
    label: "Vite",
    icon: vite,
  },
  pwa: {
    color: "#5A0FC8",
    label: "PWA",
    icon: pwa,
  },
  python: {
    color: "#3776AB",
    label: "Python",
    icon: python,
  },
  php: {
    color: "#777BB4",
    label: "PHP",
    icon: php,
  },
  figma: {
    color: "#F24E1E",
    label: "Figma",
    icon: figma,
  },  nestjs: {
    color: "#E0234E",
    label: "NestJS",
    icon: nestjs,
  },
  typeorm: {
    color: "#FE0803",
    label: "TypeORM",
    icon: typeorm,
  },
  vercelAiSdk: {
    color: "currentColor",
    label: "Vercel AI SDK",
    icon: vercel,
  },
  zod: {
    color: "#408AFF",
    label: "Zod",
    icon: zod,
  },
  mcp: {
    color: "currentColor",
    label: "MCP",
    icon: modelcontextprotocol,
  },
  transformersjs: {
    color: "#FFD21E",
    label: "Transformers.js",
    icon: huggingface,
  },
  tanstackQuery: {
    color: "#FF4154",
    label: "TanStack Query",
    icon: reactquery,
  },
  shadcn: {
    color: "currentColor",
    label: "shadcn",
    icon: shadcnui,
  },
  netlify: {
    color: "#00C7B7",
    label: "Netlify",
    icon: netlify,
  },
  cloudflarePages: {
    color: "#F38020",
    label: "Cloudflare Pages",
    icon: cloudflarepages,
  },
  ga4: {
    color: "#E37400",
    label: "GA4",
    icon: googleanalytics,
  },
  claudeCode: {
    color: "#D97757",
    label: "Claude Code",
    icon: claude,
  },
  // Sin icono en simple-icons: se muestran solo con el nombre.
  playwright: {
    color: "currentColor",
    label: "Playwright",
  },
  pgvector: {
    color: "currentColor",
    label: "pgvector",
  },
  insforge: {
    color: "currentColor",
    label: "InsForge",
  },
  gpt4oMini: {
    color: "currentColor",
    label: "gpt-4o-mini",
  },
  orama: {
    color: "currentColor",
    label: "Orama",
  },
  webWorker: {
    color: "currentColor",
    label: "Web Worker",
  },
  recharts: {
    color: "currentColor",
    label: "Recharts",
  },
};